<?php
use Aot\RussianMorphology\Slovo;

/**
 * Created by PhpStorm.
 * User: p.semenyuk
 * Date: 03.08.2015
 * Time: 14:12
 */

/** @var \Aot\RussianMorphology\Slovo $slovo */

$index = 1;
$tds = [];

foreach (\Aot\RussianMorphology\ChastiRechi\MorphologyRegistry::getClasses() as $id => $variants) {
    $name = \Aot\RussianMorphology\ChastiRechi\MorphologyRegistry::getNames()[$id];
    $tds[] = "<th title='{$name}' style='font-size: 10px;'>{$name}</th>";
    $index++;
}

echo join('', $tds);