<?php
/** @var array $post */
?>
<form name="form[rules_form]">
    <table border="1">
        <caption>Выберите правила</caption>
        <tr>
            <td>
                <label><input type="checkbox" name="form[rules_form][][rule][1]"
                        <?= $post['form']['rules_form']['rule']['1'] ?>/> правило 1</label>
            </td>
            <td>
                <label><input type="checkbox" name="form[rules_form][rule][2]"
                        <?= $post['form']['rules_form']['rule']['2'] ?>/> правило 2</label>
            </td>
            <td>
                <label><input type="checkbox" name="form[rules_form][rule][3]"
                        <?= $post['form']['rules_form']['rule']['3'] ?>/> правило 3</label>
            </td>
            <td>
                <label><input type="checkbox" name="form[rules_form][rule][4]"
                        <?= $post['form']['rules_form']['rule']['4'] ?>/> правило 4</label>
            </td>
        </tr>
    </table>

    <input type="hidden" name="form[rules_form][submit]" value="ok">
</form>