@startuml

abstract class Predlodzenie


class SSP extends Predlodzenie

class SPP extends Predlodzenie

abstract class Chasti

Chasti--*Predlodzenie

abstract class ChleniPredlodzenia extends Chasti
class INOE extends Chasti
abstract class Punctuacia extends Chasti



class Tochka extends Punctuacia
class Zapitaya extends Punctuacia
class Tire extends Punctuacia
class TochkaSZapatoy extends Punctuacia
class Dvoetochie extends Punctuacia
class DRUGOE extends Punctuacia

class Podlezhachee extends ChleniPredlodzenia
class Skazuemoe extends ChleniPredlodzenia
class Dopolnenie extends ChleniPredlodzenia
class Opredelenie extends ChleniPredlodzenia
class Obstoyatelstvo extends ChleniPredlodzenia



@enduml