<?php
/**
 * Created by PhpStorm.
 * User: p.semenyuk
 * Date: 04.07.2015
 * Time: 23:04
 */

namespace Aot\Sviaz\SequenceMember\Word;

use Aot\RussianMorphology\Slovo;

class WordWithPreposition extends Base
{
    /** @var  Slovo */
    protected $predlog;

    protected function __construct(Slovo $slovo, Slovo $predlog)
    {
        parent::__construct($slovo); // TODO: Change the autogenerated stub

        $this->predlog = $predlog;

    }

    public static function create(Slovo $slovo, Slovo $predlog = null)
    {
        assert('$predlog !== null');

        return new static($slovo, $predlog);
    }

}