<?php
/**
 * Created by PhpStorm.
 * User: p.semenyuk
 * Date: 04.07.2015
 * Time: 23:04
 */

namespace Aot\Sviaz\SequenceMember\Word;

use Aot\RussianMorphology\Slovo;

class WordWithPreposition extends Base
{
    /** @var  \Aot\RussianMorphology\ChastiRechi\Predlog\Base */
    protected $predlog;

    /**
     * @return \Aot\RussianMorphology\ChastiRechi\Predlog\Base
     */
    public function getPredlog()
    {
        return $this->predlog;
    }

    protected function __construct(Slovo $slovo, \Aot\RussianMorphology\ChastiRechi\Predlog\Base $predlog)
    {
        parent::__construct($slovo); // TODO: Change the autogenerated stub

        $this->predlog = $predlog;

    }

    public static function create(Slovo $slovo, \Aot\RussianMorphology\ChastiRechi\Predlog\Base $predlog = null)
    {
        assert($predlog !== null);

        return new static($slovo, $predlog);
    }

}